services:
    _defaults:
        autowire: true
        autoconfigure: true

    Iterica\Navigation\Navigation:
        calls:
            - [setExtensions, [!tagged_iterator navigation.extension]]
        public: true

    Iterica\NavigationBundle\Templating\Twig\NavigationExtension:
        tags:
            - { name: twig.extension, alias: navigation }

    Iterica\NavigationBundle\Service\ConfigTranslationExtractor:
        tags:
            - {name: jms_translation.file_visitor, alias: navigation_visitor}
        public: true

    Iterica\NavigationBundle\Extension\RouteExtension: ~
    Iterica\NavigationBundle\Extension\SecurityExtension: ~
